// flow-typed signature: 0f37b74e6d7e68b7d83ec3e92707423e
// flow-typed version: <<STUB>>/react-svg_v^4.0.2/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-svg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-svg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-svg/dist/ReactSVG' {
  declare module.exports: any;
}

declare module 'react-svg/dist/ReactSVG.min' {
  declare module.exports: any;
}

declare module 'react-svg/examples/basic/index' {
  declare module.exports: any;
}

declare module 'react-svg/examples/issue-49/fill/index' {
  declare module.exports: any;
}

declare module 'react-svg/examples/issue-49/swap/index' {
  declare module.exports: any;
}

declare module 'react-svg/examples/issue-68/index' {
  declare module.exports: any;
}

declare module 'react-svg/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-svg/dist/ReactSVG.js' {
  declare module.exports: $Exports<'react-svg/dist/ReactSVG'>;
}
declare module 'react-svg/dist/ReactSVG.min.js' {
  declare module.exports: $Exports<'react-svg/dist/ReactSVG.min'>;
}
declare module 'react-svg/examples/basic/index.js' {
  declare module.exports: $Exports<'react-svg/examples/basic/index'>;
}
declare module 'react-svg/examples/issue-49/fill/index.js' {
  declare module.exports: $Exports<'react-svg/examples/issue-49/fill/index'>;
}
declare module 'react-svg/examples/issue-49/swap/index.js' {
  declare module.exports: $Exports<'react-svg/examples/issue-49/swap/index'>;
}
declare module 'react-svg/examples/issue-68/index.js' {
  declare module.exports: $Exports<'react-svg/examples/issue-68/index'>;
}
declare module 'react-svg/lib/index.js' {
  declare module.exports: $Exports<'react-svg/lib/index'>;
}
